#!/usr/bin/env python3
"""
Extract BBS frames for a PxQ 2D mesh and output C-formatted data.

Usage: python3 extract_bbs_frames.py <rows> <cols> <N_chunks_for_ordering>

This runs the full BBS pipeline:
  1. Compute limitation matrix
  2. Generate wavefront frames (8 directed HD matchings)
  3. Order frames (urgency-based simulation)
  4. Optimize frames (edge swapping)
  5. Output as C arrays for bcast_2dmesh.c
"""

import sys
import os

# Add parent Topology dir to path so we can import BBS functions
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'Topology', '2Dmesh'))

import numpy as np

# Import key functions from BBS.py
from BBS import (
    compute_2d_mesh_limitation_matrix,
    generate_wavefront_frames_rectangular,
    order_frames,
    optimize_frames_rectangular_aggressive,
)


def frames_to_c(frames, p, q):
    """Convert numpy frame matrices to C array initializers."""
    n = p * q
    num_frames = len(frames)

    # Extract directed edges from each frame
    all_edges = []
    for f_idx, frame in enumerate(frames):
        edges = []
        for i in range(n):
            for j in range(n):
                if frame[i, j] > 0:
                    edges.append((i, j))
        all_edges.append(edges)

    # Print diagnostic info
    print(f"/* BBS frames for {p}x{q} 2D mesh (root=0, half-duplex) */")
    print(f"/* Generated by extract_bbs_frames.py */")
    print(f"/* {num_frames} frames, each a vertex-disjoint directed matching */")
    print()

    # Verify half-duplex: each node at most once per frame
    for f_idx, edges in enumerate(all_edges):
        nodes_used = set()
        for s, d in edges:
            assert s not in nodes_used, f"Frame {f_idx}: node {s} appears twice!"
            assert d not in nodes_used, f"Frame {f_idx}: node {d} appears twice!"
            nodes_used.add(s)
            nodes_used.add(d)
        print(f"/* Frame {f_idx}: {len(edges)} edges, "
              f"nodes involved: {len(nodes_used)}/{n} */")

    print()

    # Print MAX_EDGES_PER_FRAME
    max_edges = max(len(e) for e in all_edges)
    print(f"#define NUM_BBS_FRAMES      {num_frames}")
    print(f"#define MAX_EDGES_PER_FRAME {max_edges + 1}")  # +1 for safety
    print()

    # Print sizes
    sizes = [len(e) for e in all_edges]
    print(f"static int BBS_FRAME_SIZES[NUM_BBS_FRAMES] = {{")
    print(f"    {', '.join(str(s) for s in sizes)}")
    print(f"}};")
    print()

    # Print frame data
    print(f"static frame_edge_t BBS_FRAMES[NUM_BBS_FRAMES][MAX_EDGES_PER_FRAME] = {{")
    for f_idx, edges in enumerate(all_edges):
        edge_strs = [f"{{{s},{d:2d}}}" for s, d in edges]
        print(f"    /* Frame {f_idx} ({len(edges)} edges) */")
        print(f"    {{ {', '.join(edge_strs)} }},")
    print(f"}};")


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <rows> <cols> [N_for_ordering]",
              file=sys.stderr)
        sys.exit(1)

    p = int(sys.argv[1])
    q = int(sys.argv[2])
    N = int(sys.argv[3]) if len(sys.argv) > 3 else 100
    n = p * q

    print(f"Generating BBS frames for {p}x{q} mesh ({n} nodes), "
          f"N={N} for ordering...", file=sys.stderr)

    # Step 1: Limitation matrix
    L_int = compute_2d_mesh_limitation_matrix(p, q)
    print(f"Limitation matrix sum: {np.sum(L_int)}", file=sys.stderr)

    # Step 2: Wavefront frame generation
    frames = generate_wavefront_frames_rectangular(L_int, p, q, num_frames=8)

    # Step 3: Repair if needed
    stacked = sum(frames)
    diff = L_int - stacked.astype(L_int.dtype)
    if np.any(diff != 0):
        print("Repairing frames...", file=sys.stderr)
        for i in range(n):
            for j in range(n):
                while diff[i, j] > 0:
                    for frame in frames:
                        if frame[i, j] == 0:
                            frame[i, j] = 1
                            diff[i, j] -= 1
                            break
                while diff[i, j] < 0:
                    for frame in frames:
                        if frame[i, j] == 1:
                            frame[i, j] = 0
                            diff[i, j] += 1
                            break

    # Step 4: Order frames
    r_dim = 0  # 2D
    frames = order_frames(frames, p, q, r_dim, N)

    # Step 5: Optimize frames
    frames = optimize_frames_rectangular_aggressive(frames, p, q, r_dim)

    # Output C code
    frames_to_c(frames, p, q)


if __name__ == "__main__":
    main()
